<a href="https://colab.research.google.com/github/Ruturajsinh2839/woc5.0-ml-weather-prediction-case-study--Ruturajsinh-/blob/main/Woc5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
x = pd.read_csv('/content/drive/MyDrive/Copy of Youtube Influencer Analysis - Updated.csv',encoding ='cp1252')

In [4]:
x.isnull()

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,...,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
901,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
902,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
903,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
904,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [5]:
x.fillna(value = 0)

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,...,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,Male,40200,7964284,00:30:41,"1,841.00",...,Yes,0,419,8/6/2022,1080,462,12.0,No,1,Akhil Teja
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,Male,920000,137535681,00:14:24,864.00,...,Yes,1,189,6/15/2022,1080,251,12.0,Yes,2,Akhil Teja
2,https://www.youtube.com/watch?v=_8gfCdt3H00&t=87s,878,"Customer Psychology, Four Views Of Consumer De...",https://www.youtube.com/channel/UCcIUnCsBfONvb...,Virda Warsi,Female,458,72945,0:08:12,492.00,...,Yes,0,0,0,720,158,0.0,No,0,Syed safdar
3,https://www.youtube.com/watch?v=_CkFNJgKsFs,"9,965",Top countries with proven natural gas reserves,https://www.youtube.com/c/trtworld,TRT,0,1680000,541653219,0:01:06,66.00,...,Yes,0,77,9/22/2022,1080,46509,48.0,No,20,Syed safdar
4,https://www.youtube.com/watch?v=_GFkHA5EZdE,"39,780,561",73 Questions With Selena Gomez,Vogue - YouTube,Vogue,0,12100000,3600496171,0:07:40,460.00,...,Yes,0,28221,9/23/2022,1080,2872,113.0,No,1,Rahul Singh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,https://www.youtube.com/watch?v=GS18WawA-t0,"6,892",Calming mashup of Islamic Nasheed 2022 | Isami...,https://www.youtube.com/c/SahilOnlineTVnews,Sahil Online TV News,0,594000,129926690,00:13:47,827.00,...,Yes,0,15,10/4/2022,1080,5024,36.0,No,1,Mafaz Ali
901,https://www.youtube.com/watch?v=_tc_APkjH2Q,"16,554",Amchi Nawayat Mehfil hee,https://www.youtube.com/sahilonline,Sahil Online TV News,0,594000,129926690,00:06:44,404.00,...,Yes,2,0,10/4/2022,720,5024,36.0,No,1,Mafaz Ali
902,https://www.youtube.com/watch?v=Xfj4osSYfhU,"32,798",Aas ge Kaagaz,https://www.youtube.com/sahilonline,Sahil Online Bhatkal,0,23500,5104872,00:06:24,384.00,...,Yes,3,0,8/4/2022,720,1018,13.0,No,1,Mafaz Ali
903,https://www.youtube.com/watch?v=mGEHqwVz0eI,"1,503",Anjuman Tarana by ABHS Students | Anjuman Anju...,https://www.youtube.com/sahilonline,Sahil Online Bhatkal,0,23500,5104872,00:04:39,279.00,...,Yes,3,0,8/4/2022,1080,1018,13.0,No,1,Mafaz Ali
904,https://www.youtube.com/watch?v=UGATpt0I4vA,"429,966",Jhulan Goswami Final Over in ODIs | ENG vs IND...,https://www.youtube.com/c/SonySportsNetwork,Sony Sports Network,0,3980000,728858923,00:01:21,81.00,...,Yes,3,0,10/4/2022,1080,3014,124.0,No,0,Mafaz Ali

In [6]:
x.drop(["Creator Gender","Video Description","Community Engagement (Posts per week)","No of Playlist","Subtitle","Date of the Last Comment"],axis=1)

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,Date of Video Upload,No of Likes,Language of the Video,Hashtags,No of Comments,Maximum Quality of the Video,No of Videos the Channel,Premiered or Not,Intern Who Collected the Data
0,https://www.youtube.com/watch?v=_0fUOJ55gis,"146,059",Samse - Didupe Off-road Royal Enfield Himalayan,https://www.youtube.com/c/sriharick,srihari ck,40200,7964284,00:30:41,"1,841.00",7/29/2022,6700.0,Kannada,0,419,1080,462,No,Akhil Teja
1,https://www.youtube.com/watch?v=_70MSLPRfZI,"231,969",Bhoom Baddhal Web Series,https://www.youtube.com/c/ChaibisketTelugu,Chai Bisket,920000,137535681,00:14:24,864.00,5/22/2022,7800.0,Telugu,1,189,1080,251,Yes,Akhil Teja
2,https://www.youtube.com/watch?v=_8gfCdt3H00&t=87s,878,"Customer Psychology, Four Views Of Consumer De...",https://www.youtube.com/channel/UCcIUnCsBfONvb...,Virda Warsi,458,72945,0:08:12,492.00,2/9/2021,858.0,Hindi,0,0,720,158,No,Syed safdar
3,https://www.youtube.com/watch?v=_CkFNJgKsFs,"9,965",Top countries with proven natural gas reserves,https://www.youtube.com/c/trtworld,TRT,1680000,541653219,0:01:06,66.00,9/13/2022,188.0,English,0,77,1080,46509,No,Syed safdar
4,https://www.youtube.com/watch?v=_GFkHA5EZdE,"39,780,561",73 Questions With Selena Gomez,Vogue - YouTube,Vogue,12100000,3600496171,0:07:40,460.00,3/21/2017,901000.0,English,0,28221,1080,2872,No,Rahul Singh
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,https://www.youtube.com/watch?v=GS18WawA-t0,"6,892",Calming mashup of Islamic Nasheed 2022 | Isami...,https://www.youtube.com/c/SahilOnlineTVnews,Sahil Online TV News,594000,129926690,00:13:47,827.00,9/29/2022,235.0,Urdu + Arabic,0,15,1080,5024,No,Mafaz Ali
901,https://www.youtube.com/watch?v=_tc_APkjH2Q,"16,554",Amchi Nawayat Mehfil hee,https://www.youtube.com/sahilonline,Sahil Online TV News,594000,129926690,00:06:44,404.00,8/6/2017,117.0,Nawayathi,2,0,720,5024,No,Mafaz Ali
902,https://www.youtube.com/watch?v=Xfj4osSYfhU,"32,798",Aas ge Kaagaz,https://www.youtube.com/sahilonline,Sahil Online Bhatkal,23500,5104872,00:06:24,384.00,1/3/2021,1.0,Nawayathi,3,0,720,1018,No,Mafaz Ali
903,https://www.youtube.com/watch?v=mGEHqwVz0eI,"1,503",Anjuman Tarana by ABHS Students | Anjuman Anju...,https://www.youtube.com/sahilonline,Sahil Online Bhatkal,23500,5104872,00:04:39,279.00,3/6/2022,1.0,Urdu,3,0,1080,1018,No,Mafaz Ali
904,https://www.youtube.com/watch?v=UGATpt0I4vA,"429,966",Jhulan Goswami Final Over in ODIs | ENG vs IND...,https://www.youtube.com/c/SonySportsNetwork,Sony Sports Network,3980000,728858923,00:01:21,81.00,9/25/2022,7600.0,English,3,0,1080,3014,No,Mafaz Ali

In [24]:
to_replace=x.notnull()
to_replace.replace(to_replace =[True,False], value =[1,0])

,Video Link,Video Views,Video Title,Channel URL,Creator Name,Creator Gender,Total Channel Subcribers,Total Chanel Views,Duration of Video,Duration in Seconds,...,Video Description,Hashtags,No of Comments,Date of the Last Comment,Maximum Quality of the Video,No of Videos the Channel,No of Playlist,Premiered or Not,Community Engagement (Posts per week),Intern Who Collected the Data
0,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,1,1,1,1,1,1,1,1,1,1,...,1,1,1,0,1,1,1,1,1,1
3,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
900,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
901,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
902,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
903,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
904,1,1,1,1,1,0,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1